#!/usr/bin/env python3

import fiddler.fiddler_api as fdl
import logging
from pathlib import Path


FIDDLER_ENDPOINT = 'https://trial.fiddler.ai'
FIDDLER_TOKEN = 'pD8COC39v0_O-dKBCijuOnpvGwsDr_xSvGTfSCy2B5s'
ORG_ID = 'bug-bash'
CLEAN = False

logging.basicConfig(level=logging.INFO)

logging.info('Deploying to fiddler')
api = fdl.FiddlerApi(FIDDLER_ENDPOINT, ORG_ID, FIDDLER_TOKEN)
logging.info(f'Connected to fiddler at: {FIDDLER_ENDPOINT}')


datasets = [
    '20news',
    'bank_churn',
    'heart_disease',
    'imdb_rnn',
    'iris',
    'p2p_loans',
    'titanic',
    'winequality',
]

models = {
    #'bank_churn': ['bank_churn'],
    #'heart_disease': ['heart_disease'],
    #'imdb_rnn': ['imdb_rnn', 'imdb_rnn_test'],
    #'iris_classification': ['iris'],
    #'lending': ['logreg-all', 'logreg-simple', 'xgboost-simple-sagemaker'],
    'newsgroup': ['classifier'],
    'titanic': ['sklearn_pipeline'],
    'wine_quality': ['linear_model_wine_regressor', 'dnn_wine_regressor'],
}

if CLEAN:
    for dataset in datasets:
        logging.info(f'Deleting dataset {dataset}')
        api.delete_dataset(dataset)
    for project, model in models.items():
        logging.info(f'Deleting project {project}')
        api.delete_project(project)

#for dataset in datasets:
    #logging.info(f'uploading dataset {dataset}')
    #api.upload_dataset_from_dir(dataset, Path('datasets') / dataset)

logging.info(f'current_datasets = {api.list_datasets()}')

for project, models in models.items():
    logging.info(f'create project: {project}')
    api.create_project(project)
    for model in models:
        logging.info(f'uploading model {model}')
        api.upload_model_package(Path(project) / model, project, model)

logging.info('Done')
